### ISSUE TITLE
thanks! and heads up on a similar graphql wrapper

### ISSUE THREAD

**Issue by tlambert03** [joemans3/fpbase-client#1]
Hey @joemans3, thanks for making this package.  I just accidentally stumbled upon it.

Wanted to let you know that I also just made a wrapper (https://github.com/tlambert03/fpbasepy or `pip install fpbase`), but using the graphql API instead of the REST API (side note: apologies for the confusing dual APIs... i made the REST API first but later used the graphql API more for internal usage... so that got more attention).

Anyway, since it looks like you were looking for a similar tool, let me know if you have any feature requests on that end... or if I can help out here.. (the local sql db feature is quite nice 👍)

cheers

**Comment by joemans3** [comment]
Hey @tlambert03! Thanks for checking it out! I only built this package for myself but made it public since GitHub CI isn't free :( (apparently). 

I've been developing a "realistic" microscopy simulation package that models excitation laser PSF, stage movement, emission PSF and fluorophore kinetics (think of it as an extension of https://academic.oup.com/bioinformatics/article/32/15/2394/1742825). Since this required knowledge of some of these parameters in the FPBase I thought it might be useful to have a local DB for users to input various fluorophore parameters. It is currently not useful (even to me tbh) since I'm still figuring out the best way to structure the data in my simulation package. 

On a side note, I've built an abstracted version of it here: (https://github.com/joemans3/SMS_BP), which only focuses on sptPALM and defining dense molecular clusters (which can themselves move in time). 

I'm still new to API design and the like so I don't really understand graphql ( I've just been doing simulation/computational coding), but as I formalize my needs for the package I will reach out! I only made a local DB feature because I wanted to query the spectra. But there was no documentation on the website: https://www.fpbase.org/api/. So I just made it so that there is an initial downloading of all the entries and then spectra can be queried. (I'm sure there is a better way).

Thanks for reaching out, let me know if there is any naming conflicts with the pypi packages/github name. I can make this private if you need it. 

Best,
Baljyot Parmar

**Comment by tlambert03** [comment]
> I've been developing a "realistic" microscopy simulation package that models excitation laser PSF, stage movement, emission PSF and fluorophore kinetics (think of it as an extension of https://academic.oup.com/bioinformatics/article/32/15/2394/1742825)

wow, me too :joy:!  https://github.com/tlambert03/microsim

and honestly, this fpbasepy module was originally a [module in that package](https://github.com/tlambert03/microsim/blob/main/src/microsim/fpbase.py) that I'm just pulling out to use elsewhere. 

> I've built an abstracted version of it here: (https://github.com/joemans3/SMS_BP), which only focuses on sptPALM and defining dense molecular clusters (which can themselves move in time).

those are awesome.  I have wanted (but not yet started) to integrate motion models into the microsim Simulation schema as well.  I have one user who's been simulating molecular motors for testing kymograph analysis, and she did something ad hoc.  But I'd love to be able to use your models too.  I'll try to have a closer look in the near future.  thanks for that link

> so I don't really understand graphql ...

yeah, graphql can be a bit opaque; basic concept is that, unlike rest, (where you have a url that's dedicated to returning a relatively standardized packet of info) with graphql you have a single endpoint (https://www.fpbase.org/graphql) and the *query* contains the structure of the data you want to retrieve back.  So, for example, using the fpbasepy repo I mentioned previously, you can do a fully custom query like this:

```python
import fpbase

data = fpbase.graphql_query('{ proteins { name states { name qy extCoeff } } }')
```

where that `'{ proteins { name states { name qy extCoeff } } }'` string there conforms to the schema structure described in the docs at https://www.fpbase.org/graphql (click the little docs icon at the top left corner to explore the schema and fields available


>  But there was no documentation on the website: https://www.fpbase.org/api/

I know 😞 I'm sorry.  there's mention of it at https://help.fpbase.org/api/introduction ... but i'm sure that that vast majority of people find that first link you mentioned before the second one.  That's totally my bad, and I need to update that page. 


> Thanks for reaching out, let me know if there is any naming conflicts with the pypi packages/github name. I can make this private if you need it.

I have no concerns about that at all.  go nuts :)

**Comment by joemans3** [comment]
Oh Cool! That was exactly my vision for the simulations (re: https://github.com/tlambert03/microsim)! I guess I know what to read through tonight :). 

Just a note on the motion modules. It's simulating bounded fractional Brownian motion in 3D. To make the computation fast, I needed to assume the cell is a 3D box. Then, I could simulate each dimension with bounds (since along x you always know z,y) and then compose it together to make the final trajectory. This works the same way for the "condensate" or "dense molecular region". You can think of the condensate as a time-dependent probability distribution on the space of the cell: dense regions are just defined as cell space in which a molecule has a higher probability to "exist", importantly this probability can shift in time. This was mainly used to study the ability of a spot detection method I developed to study molecular clusters in fixed cell PALM data. (I'm procrastinating on finishing the manuscript, but I can ping you when I have a biorxiv out if you are interested.)

The motions (D, alpha) can also shift during the simulation based on a simple markov chain. I have a general user guide here: https://joemans3.github.io/SMS_BP/User_Guide_MD/. This reminds me, that there are a few typos and errors which I didn't fix before in that document. This should motivate me to do so now!

Let me know if I can help in any way, I would like to contribute (or learn to at least) a motion module to your package. I need to figure out an efficient way to represent cell space and then simulate a bounded FBM on it.

Thanks,
Baljyot

**Comment by tlambert03** [comment]
very cool, thanks for the info!  Yeah feel free to reach out, both/either when put out the preprint, or if you'd like to see if it could be incorporated into microsim.  fwiw, i would love it if microsim didn't have to reinvent the wheel for stuff like what you're working on, but hope to make more of a clear modular place to "drop in" cool bits of functionality like that.  of course, it remains to be seen whether that's actually possible.  
all good stuff. thanks

**Comment by tlambert03** [comment]
I'll close this, issue, since there's no real action to take.  just wanted to say hi :)
